version: 2.1
executors:
  my-docker-image:
    docker:
      - image: cimg/base:stable
jobs:
  test:
    executor: my-docker-image
    steps:
      - checkout
      - run: |
          pip install docker-compose
workflows:
  my-custom-workflow:
    jobs:
      - test